# Generated by Django 5.0.6 on 2024-05-08 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="user",
            new_name="username",
        ),
        migrations.RenameField(
            model_name="driver",
            old_name="user",
            new_name="username",
        ),
    ]
