# Generated by Django 5.0.6 on 2024-05-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0008_alter_driver_options_driver_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={},
        ),
        migrations.RemoveField(
            model_name="driver",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="driver",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="driver",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
    ]
