# Generated by Django 5.0.6 on 2024-05-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0009_alter_driver_options_remove_driver_date_joined_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="id",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="id",
        ),
        migrations.AlterField(
            model_name="customer",
            name="username",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="driver",
            name="username",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
