# Generated by Django 5.0.6 on 2024-05-12 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0010_remove_customer_id_remove_driver_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riderequest",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="booking.customer"
            ),
        ),
    ]
