# Generated by Django 5.0.6 on 2024-05-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0013_rename_username_riderequest_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riderequest",
            name="customer",
            field=models.CharField(max_length=20),
        ),
    ]
